### ISSUE TITLE
SVG gradient layer

### ISSUE THREAD

**Issue by JoshuaLaughton** [ComputationalThermodynamics/MAGEMinApp.jl#18]
When using the "Download plot" option to save a P-T diagram as an SVG, a gradient layer with a plasma colourmap is always overlain on the plot.
<img width="500" alt="Screenshot 2024-05-10 at 10 30 58 AM" src="https://github.com/ComputationalThermodynamics/MAGEMinApp.jl/assets/72035374/998fc91b-794a-4058-9ca6-125d5ccc3548">

**Comment by NicolasRiel** [comment]
I am not sure this is coming from the export of the svg. I think this comes from the svg reader. 

What are you using? Inkscape or Illustrator?

**Comment by JoshuaLaughton** [comment]
You're right! I was using Affinity Designer but I tried Inkscape and this does not happen. Thanks!

**Comment by NicolasRiel** [comment]
Awesome!
Sorry for the late answer, I was not notified for the issues.
Also, I think that once opened in Inkscape it should be able to export it for Affinity Designer to avoid the bug you described.
